# Generated by Django 5.1.3 on 2026-06-22 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='labels',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
