# Generated by Django 5.1.3 on 2026-06-26 11:14

import chat.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_message_delivery_failed'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=chat.models.chat_image_upload_to),
        ),
    ]
