# Generated by Django 5.1.3 on 2026-06-26 12:01

import chat.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_canonical_labels'),
    ]

    operations = [
        migrations.CreateModel(
            name='BroadcastImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=chat.models.broadcast_image_upload_to)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('broadcast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='chat.broadcast')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
