# Generated by Django 5.1.3 on 2026-04-28 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to='accounts.user')),
                ('full_name', models.CharField(max_length=255)),
                ('age', models.PositiveSmallIntegerField()),
                ('birthplace_region', models.CharField(choices=[('andijon', 'Andijon'), ('buxoro', 'Buxoro'), ('fargona', 'Farg‘ona'), ('jizzax', 'Jizzax'), ('namangan', 'Namangan'), ('navoiy', 'Navoiy'), ('qashqadaryo', 'Qashqadaryo'), ('qoraqalpogiston', 'Qoraqalpog‘iston Respublikasi'), ('samarqand', 'Samarqand'), ('sirdaryo', 'Sirdaryo'), ('surxandaryo', 'Surxandaryo'), ('toshkent_shahar', 'Toshkent shahar'), ('toshkent_viloyat', 'Toshkent viloyat'), ('xorazm', 'Xorazm')], max_length=32)),
                ('current_residence_germany', models.CharField(max_length=255)),
                ('height_weight', models.CharField(blank=True, default='', max_length=128)),
                ('education', models.CharField(max_length=512)),
                ('profession_hobbies', models.TextField()),
                ('marital_status', models.TextField()),
                ('family_info', models.TextField()),
                ('nationality_languages', models.TextField()),
                ('religion', models.TextField(blank=True, default='')),
                ('germany_status', models.TextField(blank=True, default='')),
                ('self_description', models.TextField()),
                ('partner_expectations', models.TextField()),
                ('contact_info', models.CharField(max_length=255)),
                ('tariff', models.CharField(choices=[('basic', 'Basic'), ('standart', 'Standart')], max_length=16)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=16)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
